mobile first
GSG-CF04/Blearning-team4 pull request #20
Opened 2021-10-22 12:42 UTC by IsraaHamdi

2021-10-23 13:30 UTC, yaqootturman requested changes

2021-10-23 13:30 UTC, yaqootturman commented on home/home.html
> +                    <span><a href="">Mathematics</a></span>
I can't comment on merged parts, so I will write my comments here:
- You can't called a class "padding" in line 21, its not descriptive for the header which should be
- I don't prefer push empty tags as 23,24,25 lines
- videos aren't run which a problem, and scrolling is not allowed too

2021-10-25 14:53 UTC, yaqootturman approved these changes

2021-10-25 15:12 UTC, MohammedDahalan approved these changes
coooool

2021-10-25 15:12 UTC, merged